<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Domain\TrainStation.Domain\Exceptions\" />
    <Folder Include="Domain\TrainStation.Domain\Enums\" />
  </ItemGroup>

</Project>
